export default {
  "?xml":"",
  "Publication_MarketDocument":{
     "mRID":"24a25c7bd8184f27b786aab51a8262e1",
     "revisionNumber":1,
     "type":"A44",
     "sender_MarketParticipant.mRID":"10X1001A1001A450",
     "sender_MarketParticipant.marketRole.type":"A32",
     "receiver_MarketParticipant.mRID":"10X1001A1001A450",
     "receiver_MarketParticipant.marketRole.type":"A33",
     "createdDateTime":"2023-12-03T12:00:08Z",
     "period.timeInterval":{
        "start":"2023-12-02T23:00Z",
        "end":"2023-12-03T23:00Z"
     },
     "TimeSeries":{
        "mRID":1,
        "businessType":"A62",
        "in_Domain.mRID":"10Y1001A1001A47J",
        "out_Domain.mRID":"10Y1001A1001A47J",
        "currency_Unit.name":"EUR",
        "price_Measure_Unit.name":"MWH",
        "curveType":"A01",
        "Period":{
           "timeInterval":{
              "start":"2023-12-02T23:00Z",
              "end":"2023-12-03T23:00Z"
           },
           "resolution":"PT60M",
           "Point":[
              {
                 "position":1,
                 "price.amount":105.15
              },
              {
                 "position":2,
                 "price.amount":99.7
              },
              {
                 "position":3,
                 "price.amount":94.97
              },
              {
                 "position":4,
                 "price.amount":88.83
              },
              {
                 "position":5,
                 "price.amount":92.35
              },
              {
                 "position":6,
                 "price.amount":89.52
              },
              {
                 "position":7,
                 "price.amount":88.86
              },
              {
                 "position":8,
                 "price.amount":92.13
              },
              {
                 "position":9,
                 "price.amount":97.02
              },
              {
                 "position":10,
                 "price.amount":100.15
              },
              {
                 "position":11,
                 "price.amount":104.96
              },
              {
                 "position":12,
                 "price.amount":105.07
              },
              {
                 "position":13,
                 "price.amount":103.68
              },
              {
                 "position":14,
                 "price.amount":102.46
              },
              {
                 "position":15,
                 "price.amount":105.68
              },
              {
                 "position":16,
                 "price.amount":117.83
              },
              {
                 "position":17,
                 "price.amount":125.2
              },
              {
                 "position":18,
                 "price.amount":131.72
              },
              {
                 "position":19,
                 "price.amount":132.22
              },
              {
                 "position":20,
                 "price.amount":126.07
              },
              {
                 "position":21,
                 "price.amount":112.33
              },
              {
                 "position":22,
                 "price.amount":101.95
              },
              {
                 "position":23,
                 "price.amount":99.09
              },
              {
                 "position":24,
                 "price.amount":91.12
              }
           ]
        }
     }
  }
}
